[build]
  publish = "sustainable-cities"
  command = "echo 'No build command needed for static site'"

[[redirects]]
  from = "/features/*"
  to = "/features/index.html"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/auth/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/videos/*"
  [headers.values]
    Content-Type = "video/mp4"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[build.environment]
  NODE_VERSION = "18" 