[build]
  publish = "sustainable-cities"
  command = "echo 'No build command needed for static site'"

[[redirects]]
  from = "/features/*"
  to = "/features/index.html"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/auth/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 